/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment2;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JSplitPane;

/**
 *
 * @author ren
 */
public class OCMS extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OCMS.class.getName());

    /**
     * Creates new form OCMS
     */
    public OCMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleSplit = new javax.swing.JSplitPane();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        navSplit = new javax.swing.JSplitPane();
        navPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        charMenuBtn = new javax.swing.JButton();
        groupMenuBtn = new javax.swing.JButton();
        relMenuBtn = new javax.swing.JButton();
        tagMenuBtn = new javax.swing.JButton();
        searchMenuBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        cPanel = new javax.swing.JPanel();
        gPanel = new javax.swing.JPanel();
        rPanel = new javax.swing.JPanel();
        tPanel = new javax.swing.JPanel();
        sPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleSplit.setDividerSize(0);
        titleSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        titlePanel.setBackground(new java.awt.Color(102, 153, 255));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Original Character Management System");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        titleSplit.setTopComponent(titlePanel);

        navSplit.setDividerLocation(200);
        navSplit.setDividerSize(0);
        navSplit.setFocusable(false);

        navPanel.setBackground(new java.awt.Color(0, 204, 255));

        exitBtn.setBackground(new java.awt.Color(0, 153, 204));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(0, 0, 0));
        exitBtn.setText("Exit");
        exitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));
        exitBtn.addActionListener(this::exitBtnActionPerformed);

        charMenuBtn.setBackground(new java.awt.Color(0, 153, 204));
        charMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        charMenuBtn.setForeground(new java.awt.Color(0, 0, 0));
        charMenuBtn.setText("Character Menu");
        charMenuBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));
        charMenuBtn.addActionListener(this::charMenuBtnActionPerformed);

        groupMenuBtn.setBackground(new java.awt.Color(0, 153, 204));
        groupMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        groupMenuBtn.setForeground(new java.awt.Color(0, 0, 0));
        groupMenuBtn.setText("Group Menu");
        groupMenuBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));
        groupMenuBtn.addActionListener(this::groupMenuBtnActionPerformed);

        relMenuBtn.setBackground(new java.awt.Color(0, 153, 204));
        relMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        relMenuBtn.setForeground(new java.awt.Color(0, 0, 0));
        relMenuBtn.setText("Relationship Menu");
        relMenuBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));
        relMenuBtn.addActionListener(this::relMenuBtnActionPerformed);

        tagMenuBtn.setBackground(new java.awt.Color(0, 153, 204));
        tagMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tagMenuBtn.setForeground(new java.awt.Color(0, 0, 0));
        tagMenuBtn.setText("Tag Menu");
        tagMenuBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));
        tagMenuBtn.addActionListener(this::tagMenuBtnActionPerformed);

        searchMenuBtn.setBackground(new java.awt.Color(0, 153, 204));
        searchMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchMenuBtn.setForeground(new java.awt.Color(0, 0, 0));
        searchMenuBtn.setText("Search / Filter");
        searchMenuBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2));
        searchMenuBtn.addActionListener(this::searchMenuBtnActionPerformed);

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(charMenuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(groupMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(relMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(tagMenuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(searchMenuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(charMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(groupMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(relMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tagMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        navSplit.setLeftComponent(navPanel);

        mainPanel.setLayout(new java.awt.CardLayout());

        cPanel.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout cPanelLayout = new javax.swing.GroupLayout(cPanel);
        cPanel.setLayout(cPanelLayout);
        cPanelLayout.setHorizontalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        cPanelLayout.setVerticalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        mainPanel.add(cPanel, "character");

        gPanel.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout gPanelLayout = new javax.swing.GroupLayout(gPanel);
        gPanel.setLayout(gPanelLayout);
        gPanelLayout.setHorizontalGroup(
            gPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        gPanelLayout.setVerticalGroup(
            gPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        mainPanel.add(gPanel, "group");

        rPanel.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout rPanelLayout = new javax.swing.GroupLayout(rPanel);
        rPanel.setLayout(rPanelLayout);
        rPanelLayout.setHorizontalGroup(
            rPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        rPanelLayout.setVerticalGroup(
            rPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        mainPanel.add(rPanel, "relationship");

        tPanel.setBackground(new java.awt.Color(255, 51, 255));

        javax.swing.GroupLayout tPanelLayout = new javax.swing.GroupLayout(tPanel);
        tPanel.setLayout(tPanelLayout);
        tPanelLayout.setHorizontalGroup(
            tPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        tPanelLayout.setVerticalGroup(
            tPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        mainPanel.add(tPanel, "tag");

        sPanel.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout sPanelLayout = new javax.swing.GroupLayout(sPanel);
        sPanel.setLayout(sPanelLayout);
        sPanelLayout.setHorizontalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        sPanelLayout.setVerticalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        mainPanel.add(sPanel, "search");

        navSplit.setRightComponent(mainPanel);

        titleSplit.setRightComponent(navSplit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleSplit)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleSplit)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void charMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charMenuBtnActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "character");
    }//GEN-LAST:event_charMenuBtnActionPerformed

    private void groupMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupMenuBtnActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "group");
    }//GEN-LAST:event_groupMenuBtnActionPerformed

    private void relMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relMenuBtnActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "relationship");
    }//GEN-LAST:event_relMenuBtnActionPerformed

    private void tagMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagMenuBtnActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "tag");
    }//GEN-LAST:event_tagMenuBtnActionPerformed

    private void searchMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMenuBtnActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "search");
    }//GEN-LAST:event_searchMenuBtnActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OCMS().setVisible(true));
    }
    
    public void setSplitHeight(){
        // Get the screen size as a Dimension object
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Access height
        int screenHeight = (int) screenSize.getHeight();
        int screenWidth = (int) screenSize.getWidth();
        
        int height = (int) (screenHeight * 0.15);
        int width = (int) (screenWidth * 0.15);
        titleSplit.setDividerLocation(height);
        navSplit.setDividerLocation(width);

        // Lock it in place
        navSplit.addPropertyChangeListener(JSplitPane.DIVIDER_LOCATION_PROPERTY, e -> {
            navSplit.setDividerLocation(width);
        });
        titleSplit.addPropertyChangeListener(JSplitPane.DIVIDER_LOCATION_PROPERTY, e -> {
            titleSplit.setDividerLocation(width);
        });
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cPanel;
    private javax.swing.JButton charMenuBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel gPanel;
    private javax.swing.JButton groupMenuBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JSplitPane navSplit;
    private javax.swing.JPanel rPanel;
    private javax.swing.JButton relMenuBtn;
    private javax.swing.JPanel sPanel;
    private javax.swing.JButton searchMenuBtn;
    private javax.swing.JPanel tPanel;
    private javax.swing.JButton tagMenuBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JSplitPane titleSplit;
    // End of variables declaration//GEN-END:variables
}
